[mgr]
cwd = { fg = "#2b73af" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#d6a01d" }
find_position = { fg = "#c08eaf" }

marker_copied = { fg = "#428675", bg = "#428675" }
marker_cut = { fg = "#c04851", bg = "#c04851" }
marker_selected = { fg = "#d6a01d", bg = "#d6a01d" }

tab_inactive = { fg = "#4a4035" }
tab_active = { fg = "#ffffff", bg = "#4a4035"}

count_copied = { fg = "#ffffff", bg = "#428675" }
count_cut = { fg = "#ffffff", bg = "#c04851" }
count_selected = { fg = "#ffffff", bg = "#d6a01d" }

border_style = { fg = "#815c94" }

[mode]
normal_main = { fg = "#ffffff", bg = "#815c94", bold = true }
normal_alt = { fg = "#815c94", bg = "#d6d6d6" }

select_alt = { fg = "#c08eaf", bg = "#d6d6d6" }
select_main = { fg = "#ffffff", bg = "#c08eaf", bold = true }

unset_main = { fg = "#ffffff", bg = "#c04851", bold = true }
unset_alt = { fg = "#c04851", bg = "#d6d6d6" }

[status]
perm_exec = { fg = "#428675" }
perm_read = { fg = "#d6a01d" }
perm_sep = { fg = "#2b73af" }
perm_type = { fg = "#815c94" }
perm_write = { fg = "#c04851" }

progress_error = { fg = "#c04851", bg = "#ffffff" }
progress_label = { fg = "#4a4035", bg = "#ffffff" }
progress_normal = { fg = "#4a4035", bg = "#ffffff" }

[pick]
active = { fg = "#c08eaf" }
border = { fg = "#815c94" }
inactive = { fg = "#4a4035" }

[task]
title = { fg = "#815c94" }
border = { fg = "#815c94" }
hovered = { fg = "#4a4035", bg = "#d6d6d6" }

[input]
border = { fg = "#815c94" }
selected = { bg = "#d6d6d6" }

[help]
desc = { fg = "#4a4035" }
on = { fg = "#2b73af" }
run = { fg = "#c08eaf" }
hovered = { reversed = true, bold = true }
footer = { fg = "#d6d6d6", bg = "#4a4035" }

[which]
mask = { bg = "#d6d6d6" }
desc = { fg = "#4a4035" }
cand = { fg = "#2b73af" }
rest = { fg = "#945833" }

separator_style = { fg = "#918072" }

[notify]
title_info = { fg = "#2b73af" }
title_warn = { fg = "#d6a01d" }
title_error = { fg = "#c04851" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#2b73af" },
  { mime = "{audio, video}/*", fg = "#d6a01d" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#428675" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#815c94" },
  { mime = "*", fg = "#4a4035" },
]


