[mgr]
cwd = { fg = "#88b68d" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#fbb957" }
find_position = { fg = "#cf8997" }

marker_copied = { fg = "#aeb831", bg = "#aeb831" }
marker_cut = { fg = "#ed5a56", bg = "#ed5a56" }
marker_selected = { fg = "#fbb957", bg = "#fbb957" }

tab_inactive = { fg = "#c4cbcf" }
tab_active = { fg = "#1d1d1d", bg = "#c4cbcf"}

count_copied = { fg = "#1d1d1d", bg = "#aeb831" }
count_cut = { fg = "#1d1d1d", bg = "#ed5a56" }
count_selected = { fg = "#1d1d1d", bg = "#fbb957" }

border_style = { fg = "#81a2a2" }

[mode]
normal_main = { fg = "#1d1d1d", bg = "#81a2a2", bold = true }
normal_alt = { fg = "#81a2a2", bg = "#373737" }

select_alt = { fg = "#cf8997", bg = "#373737" }
select_main = { fg = "#1d1d1d", bg = "#cf8997", bold = true }

unset_main = { fg = "#1d1d1d", bg = "#ed5a56", bold = true }
unset_alt = { fg = "#ed5a56", bg = "#373737" }

[status]
perm_exec = { fg = "#aeb831" }
perm_read = { fg = "#fbb957" }
perm_sep = { fg = "#88b68d" }
perm_type = { fg = "#81a2a2" }
perm_write = { fg = "#ed5a56" }

progress_error = { fg = "#ed5a56", bg = "#1d1d1d" }
progress_label = { fg = "#c4cbcf", bg = "#1d1d1d" }
progress_normal = { fg = "#c4cbcf", bg = "#1d1d1d" }

[pick]
active = { fg = "#cf8997" }
border = { fg = "#81a2a2" }
inactive = { fg = "#c4cbcf" }

[task]
title = { fg = "#81a2a2" }
border = { fg = "#81a2a2" }
hovered = { fg = "#c4cbcf", bg = "#373737" }

[input]
border = { fg = "#81a2a2" }
selected = { bg = "#373737" }

[help]
desc = { fg = "#c4cbcf" }
on = { fg = "#88b68d" }
run = { fg = "#cf8997" }
hovered = { reversed = true, bold = true }
footer = { fg = "#373737", bg = "#c4cbcf" }

[which]
mask = { bg = "#373737" }
desc = { fg = "#c4cbcf" }
cand = { fg = "#88b68d" }
rest = { fg = "#cd6227" }

separator_style = { fg = "#bdaead" }

[notify]
title_info = { fg = "#88b68d" }
title_warn = { fg = "#fbb957" }
title_error = { fg = "#ed5a56" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#88b68d" },
  { mime = "{audio, video}/*", fg = "#fbb957" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#aeb831" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#81a2a2" },
  { mime = "*", fg = "#c4cbcf" },
]


