[mgr]
cwd = { fg = "#00c4d7" }

hovered = { reversed = true }
preview_hoverd = { underline = true }

find_keyword = { bold = true, fg = "#a9b852" }
find_position = { fg = "#b69cf6" }

marker_copied = { fg = "#54c794", bg = "#54c794" }
marker_cut = { fg = "#f58c81", bg = "#f58c81" }
marker_selected = { fg = "#a9b852", bg = "#a9b852" }

tab_inactive = { fg = "#dedede" }
tab_active = { fg = "#0d0f13", bg = "#dedede"}

count_copied = { fg = "#0d0f13", bg = "#54c794" }
count_cut = { fg = "#0d0f13", bg = "#f58c81" }
count_selected = { fg = "#0d0f13", bg = "#a9b852" }

border_style = { fg = "#6eb2fd" }

[mode]
normal_main = { fg = "#0d0f13", bg = "#6eb2fd", bold = true }
normal_alt = { fg = "#6eb2fd", bg = "#3e4044" }

select_alt = { fg = "#b69cf6", bg = "#3e4044" }
select_main = { fg = "#0d0f13", bg = "#b69cf6", bold = true }

unset_main = { fg = "#0d0f13", bg = "#f58c81", bold = true }
unset_alt = { fg = "#f58c81", bg = "#3e4044" }

[status]
perm_exec = { fg = "#54c794" }
perm_read = { fg = "#a9b852" }
perm_sep = { fg = "#00c4d7" }
perm_type = { fg = "#6eb2fd" }
perm_write = { fg = "#f58c81" }

progress_error = { fg = "#f58c81", bg = "#0d0f13" }
progress_label = { fg = "#dedede", bg = "#0d0f13" }
progress_normal = { fg = "#dedede", bg = "#0d0f13" }

[pick]
active = { fg = "#b69cf6" }
border = { fg = "#6eb2fd" }
inactive = { fg = "#dedede" }

[task]
title = { fg = "#6eb2fd" }
border = { fg = "#6eb2fd" }
hovered = { fg = "#dedede", bg = "#3e4044" }

[input]
border = { fg = "#6eb2fd" }
selected = { bg = "#3e4044" }

[help]
desc = { fg = "#dedede" }
on = { fg = "#00c4d7" }
run = { fg = "#b69cf6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3e4044", bg = "#dedede" }

[which]
mask = { bg = "#3e4044" }
desc = { fg = "#dedede" }
cand = { fg = "#00c4d7" }
rest = { fg = "#e58cc5" }

separator_style = { fg = "#aeaeae" }

[notify]
title_info = { fg = "#00c4d7" }
title_warn = { fg = "#a9b852" }
title_error = { fg = "#f58c81" }
 
[filetype]
rules = [
  { mime = "image/*", fg = "#00c4d7" },
  { mime = "{audio, video}/*", fg = "#a9b852" },
   
  { mime = "application/{pdf,doc,rtf}", fg = "#54c794" },
  
  { mime = "application/" },
  
  { mime = "inode/directory", fg = "#6eb2fd" },
  { mime = "*", fg = "#dedede" },
]


