# vim: ft=toml
[mgr]
cwd = { fg = "#7263aa" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#804ead" }
find_position = { fg = "#953b9d" }

marker_copied = { fg = "#c6914b", bg = "#c6914b" }
marker_cut = { fg = "#a92258", bg = "#a92258" }
marker_selected = { fg = "#804ead", bg = "#804ead" }

tab_inactive = { fg = "#dedcdf" }
tab_active = { fg = "#271c3a", bg = "#dedcdf" }

count_copied = { fg = "#271c3a", bg = "#c6914b" }
count_cut = { fg = "#271c3a", bg = "#a92258" }
count_selected = { fg = "#271c3a", bg = "#804ead" }

border_style = { fg = "#8e7dc6" }

[mode]
normal_main = { fg = "#271c3a", bg = "#8e7dc6", bold = true }
normal_alt = { fg = "#8e7dc6", bg = "#3e2d5c" }

select_alt = { fg = "#953b9d", bg = "#3e2d5c" }
select_main = { fg = "#271c3a", bg = "#953b9d", bold = true }

unset_main = { fg = "#271c3a", bg = "#a92258", bold = true }
unset_alt = { fg = "#a92258", bg = "#3e2d5c" }

[status]
perm_exec = { fg = "#c6914b" }
perm_read = { fg = "#804ead" }
perm_sep = { fg = "#7263aa" }
perm_type = { fg = "#8e7dc6" }
perm_write = { fg = "#a92258" }

progress_error = { fg = "#a92258", bg = "#271c3a" }
progress_label = { fg = "#dedcdf", bg = "#271c3a" }
progress_normal = { fg = "#dedcdf", bg = "#271c3a" }

[pick]
active = { fg = "#953b9d" }
border = { fg = "#8e7dc6" }
inactive = { fg = "#dedcdf" }

[task]
title = { fg = "#8e7dc6" }
border = { fg = "#8e7dc6" }
hovered = { fg = "#dedcdf", bg = "#3e2d5c" }

[input]
border = { fg = "#8e7dc6" }
selected = { bg = "#3e2d5c" }

[help]
desc = { fg = "#dedcdf" }
on = { fg = "#7263aa" }
run = { fg = "#953b9d" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3e2d5c", bg = "#dedcdf" }

[which]
mask = { bg = "#3e2d5c" }
desc = { fg = "#dedcdf" }
cand = { fg = "#7263aa" }
rest = { fg = "#59325c" }

separator_style = { fg = "#bebcbf" }

[notify]
title_info = { fg = "#7263aa" }
title_warn = { fg = "#804ead" }
title_error = { fg = "#a92258" }

[filetype]
rules = [
  { mime = "image/*", fg = "#804ead" },
  { mime = "{audio, video}/*", fg = "#c6914b" },

  { mime = "application/{pdf,doc,rtf}", fg = "#dedcdf" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#7263aa" },
  { mime = "inode/directory", is = "link", fg = "#7263aa" },
  { mime = "*", is = "sock", fg = "#bebcbf" },
  { mime = "*", is = "char", fg = "#918889" },
  { mime = "*", is = "exec", fg = "#c6914b" },
  { mime = "*", fg = "#dedcdf" },
  { mime = "inode/directory", fg = "#8e7dc6" },
]
