# vim: ft=toml
[mgr]
cwd = { fg = "#bed6ff" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#8ab7d9" }
find_position = { fg = "#d197d9" }

marker_copied = { fg = "#a5c261", bg = "#a5c261" }
marker_cut = { fg = "#d25151", bg = "#d25151" }
marker_selected = { fg = "#8ab7d9", bg = "#8ab7d9" }

tab_inactive = { fg = "#c7c7c5" }
tab_active = { fg = "#262626", bg = "#c7c7c5" }

count_copied = { fg = "#262626", bg = "#a5c261" }
count_cut = { fg = "#262626", bg = "#d25151" }
count_selected = { fg = "#262626", bg = "#8ab7d9" }

border_style = { fg = "#6c99bb" }

[mode]
normal_main = { fg = "#262626", bg = "#6c99bb", bold = true }
normal_alt = { fg = "#6c99bb", bg = "#535353" }

select_alt = { fg = "#d197d9", bg = "#535353" }
select_main = { fg = "#262626", bg = "#d197d9", bold = true }

unset_main = { fg = "#262626", bg = "#d25151", bold = true }
unset_alt = { fg = "#d25151", bg = "#535353" }

[status]
perm_exec = { fg = "#a5c261" }
perm_read = { fg = "#8ab7d9" }
perm_sep = { fg = "#bed6ff" }
perm_type = { fg = "#6c99bb" }
perm_write = { fg = "#d25151" }

progress_error = { fg = "#d25151", bg = "#262626" }
progress_label = { fg = "#c7c7c5", bg = "#262626" }
progress_normal = { fg = "#c7c7c5", bg = "#262626" }

[pick]
active = { fg = "#d197d9" }
border = { fg = "#6c99bb" }
inactive = { fg = "#c7c7c5" }

[task]
title = { fg = "#6c99bb" }
border = { fg = "#6c99bb" }
hovered = { fg = "#c7c7c5", bg = "#535353" }

[input]
border = { fg = "#6c99bb" }
selected = { bg = "#535353" }

[help]
desc = { fg = "#c7c7c5" }
on = { fg = "#bed6ff" }
run = { fg = "#d197d9" }
hovered = { reversed = true, bold = true }
footer = { fg = "#535353", bg = "#c7c7c5" }

[which]
mask = { bg = "#535353" }
desc = { fg = "#c7c7c5" }
cand = { fg = "#bed6ff" }
rest = { fg = "#692828" }

separator_style = { fg = "#a0a09f" }

[notify]
title_info = { fg = "#bed6ff" }
title_warn = { fg = "#8ab7d9" }
title_error = { fg = "#d25151" }

[filetype]
rules = [
  { mime = "image/*", fg = "#8ab7d9" },
  { mime = "{audio, video}/*", fg = "#a5c261" },

  { mime = "application/{pdf,doc,rtf}", fg = "#c7c7c5" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#bed6ff" },
  { mime = "inode/directory", is = "link", fg = "#bed6ff" },
  { mime = "inode/directory", fg = "#6c99bb" },
  { mime = "*", is = "sock", fg = "#a0a09f" },
  { mime = "*", is = "char", fg = "#ffc66d" },
  { mime = "*", is = "exec", fg = "#a5c261" },
  { mime = "*", fg = "#c7c7c5" },
]
