# vim: ft=toml
[mgr]
cwd = { fg = "#149bda" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#dc8a0e" }
find_position = { fg = "#b33ce8" }

marker_copied = { fg = "#17ad98", bg = "#17ad98" }
marker_cut = { fg = "#d8137f", bg = "#d8137f" }
marker_selected = { fg = "#dc8a0e", bg = "#dc8a0e" }

tab_inactive = { fg = "#c3c2c4" }
tab_active = { fg = "#2e2a31", bg = "#c3c2c4" }

count_copied = { fg = "#2e2a31", bg = "#17ad98" }
count_cut = { fg = "#2e2a31", bg = "#d8137f" }
count_selected = { fg = "#2e2a31", bg = "#dc8a0e" }

border_style = { fg = "#7864fa" }

[mode]
normal_main = { fg = "#2e2a31", bg = "#7864fa", bold = true }
normal_alt = { fg = "#7864fa", bg = "#69666b" }

select_alt = { fg = "#b33ce8", bg = "#69666b" }
select_main = { fg = "#2e2a31", bg = "#b33ce8", bold = true }

unset_main = { fg = "#2e2a31", bg = "#d8137f", bold = true }
unset_alt = { fg = "#d8137f", bg = "#69666b" }

[status]
perm_exec = { fg = "#17ad98" }
perm_read = { fg = "#dc8a0e" }
perm_sep = { fg = "#149bda" }
perm_type = { fg = "#7864fa" }
perm_write = { fg = "#d8137f" }

progress_error = { fg = "#d8137f", bg = "#2e2a31" }
progress_label = { fg = "#c3c2c4", bg = "#2e2a31" }
progress_normal = { fg = "#c3c2c4", bg = "#2e2a31" }

[pick]
active = { fg = "#b33ce8" }
border = { fg = "#7864fa" }
inactive = { fg = "#c3c2c4" }

[task]
title = { fg = "#7864fa" }
border = { fg = "#7864fa" }
hovered = { fg = "#c3c2c4", bg = "#69666b" }

[input]
border = { fg = "#7864fa" }
selected = { bg = "#69666b" }

[help]
desc = { fg = "#c3c2c4" }
on = { fg = "#149bda" }
run = { fg = "#b33ce8" }
hovered = { reversed = true, bold = true }
footer = { fg = "#69666b", bg = "#c3c2c4" }

[which]
mask = { bg = "#69666b" }
desc = { fg = "#c3c2c4" }
cand = { fg = "#149bda" }
rest = { fg = "#d41acd" }

separator_style = { fg = "#a5a3a6" }

[notify]
title_info = { fg = "#149bda" }
title_warn = { fg = "#dc8a0e" }
title_error = { fg = "#d8137f" }

[filetype]
rules = [
  { mime = "image/*", fg = "#dc8a0e" },
  { mime = "{audio, video}/*", fg = "#17ad98" },

  { mime = "application/{pdf,doc,rtf}", fg = "#c3c2c4" },

  { mime = "application/" },

  { mime = "inode/directory", fg = "#7864fa" },
  { mime = "*", is = "link", fg = "#149bda" },
  { mime = "*/", is = "link", fg = "#149bda" },
  { mime = "*", is = "sock", fg = "#a5a3a6" },
  { mime = "*", is = "char", fg = "#d65407" },
  { mime = "*", is = "exec", fg = "#17ad98" },
  { mime = "*", fg = "#c3c2c4" },
]
