# vim: ft=toml
[mgr]
cwd = { fg = "#8eaea9" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#8085ef" }
find_position = { fg = "#a07c7b" }

marker_copied = { fg = "#90773e", bg = "#90773e" }
marker_cut = { fg = "#b93934", bg = "#b93934" }
marker_selected = { fg = "#8085ef", bg = "#8085ef" }

tab_inactive = { fg = "#968684" }
tab_active = { fg = "#121213", bg = "#968684" }

count_copied = { fg = "#121213", bg = "#90773e" }
count_cut = { fg = "#121213", bg = "#b93934" }
count_selected = { fg = "#121213", bg = "#8085ef" }

border_style = { fg = "#5e62b4" }

[mode]
normal_main = { fg = "#121213", bg = "#5e62b4", bold = true }
normal_alt = { fg = "#5e62b4", bg = "#4e4b60" }

select_alt = { fg = "#a07c7b", bg = "#4e4b60" }
select_main = { fg = "#121213", bg = "#a07c7b", bold = true }

unset_main = { fg = "#121213", bg = "#b93934", bold = true }
unset_alt = { fg = "#b93934", bg = "#4e4b60" }

[status]
perm_exec = { fg = "#90773e" }
perm_read = { fg = "#8085ef" }
perm_sep = { fg = "#8eaea9" }
perm_type = { fg = "#5e62b4" }
perm_write = { fg = "#b93934" }

progress_error = { fg = "#b93934", bg = "#121213" }
progress_label = { fg = "#968684", bg = "#121213" }
progress_normal = { fg = "#968684", bg = "#121213" }

[pick]
active = { fg = "#a07c7b" }
border = { fg = "#5e62b4" }
inactive = { fg = "#968684" }

[task]
title = { fg = "#5e62b4" }
border = { fg = "#5e62b4" }
hovered = { fg = "#968684", bg = "#4e4b60" }

[input]
border = { fg = "#5e62b4" }
selected = { bg = "#4e4b60" }

[help]
desc = { fg = "#968684" }
on = { fg = "#8eaea9" }
run = { fg = "#a07c7b" }
hovered = { reversed = true, bold = true }
footer = { fg = "#4e4b60", bg = "#968684" }

[which]
mask = { bg = "#4e4b60" }
desc = { fg = "#968684" }
cand = { fg = "#8eaea9" }
rest = { fg = "#5c1c1a" }

separator_style = { fg = "#7e7278" }

[notify]
title_info = { fg = "#8eaea9" }
title_warn = { fg = "#8085ef" }
title_error = { fg = "#b93934" }

[filetype]
rules = [
  { mime = "image/*", fg = "#8085ef" },
  { mime = "{audio, video}/*", fg = "#90773e" },

  { mime = "application/{pdf,doc,rtf}", fg = "#968684" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#8eaea9" },
  { mime = "inode/directory", is = "link", fg = "#8eaea9" },
  { mime = "*", is = "sock", fg = "#7e7278" },
  { mime = "*", is = "char", fg = "#b45600" },
  { mime = "*", is = "exec", fg = "#90773e" },
  { mime = "*", fg = "#968684" },
  { mime = "inode/directory", fg = "#5e62b4" },
]
