# vim: ft=toml
[mgr]
cwd = { fg = "#b5e4f4" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#807d7c" }
find_position = { fg = "#a16a94" }

marker_copied = { fg = "#01a252", bg = "#01a252" }
marker_cut = { fg = "#db2d20", bg = "#db2d20" }
marker_selected = { fg = "#807d7c", bg = "#807d7c" }

tab_inactive = { fg = "#928f8e" }
tab_active = { fg = "#090300", bg = "#928f8e" }

count_copied = { fg = "#090300", bg = "#01a252" }
count_cut = { fg = "#090300", bg = "#db2d20" }
count_selected = { fg = "#090300", bg = "#807d7c" }

border_style = { fg = "#01a0e4" }

[mode]
normal_main = { fg = "#090300", bg = "#01a0e4", bold = true }
normal_alt = { fg = "#01a0e4", bg = "#5c5855" }

select_alt = { fg = "#a16a94", bg = "#5c5855" }
select_main = { fg = "#090300", bg = "#a16a94", bold = true }

unset_main = { fg = "#090300", bg = "#db2d20", bold = true }
unset_alt = { fg = "#db2d20", bg = "#5c5855" }

[status]
perm_exec = { fg = "#01a252" }
perm_read = { fg = "#807d7c" }
perm_sep = { fg = "#b5e4f4" }
perm_type = { fg = "#01a0e4" }
perm_write = { fg = "#db2d20" }

progress_error = { fg = "#db2d20", bg = "#090300" }
progress_label = { fg = "#928f8e", bg = "#090300" }
progress_normal = { fg = "#928f8e", bg = "#090300" }

[pick]
active = { fg = "#a16a94" }
border = { fg = "#01a0e4" }
inactive = { fg = "#928f8e" }

[task]
title = { fg = "#01a0e4" }
border = { fg = "#01a0e4" }
hovered = { fg = "#928f8e", bg = "#5c5855" }

[input]
border = { fg = "#01a0e4" }
selected = { bg = "#5c5855" }

[help]
desc = { fg = "#928f8e" }
on = { fg = "#b5e4f4" }
run = { fg = "#a16a94" }
hovered = { reversed = true, bold = true }
footer = { fg = "#5c5855", bg = "#928f8e" }

[which]
mask = { bg = "#5c5855" }
desc = { fg = "#928f8e" }
cand = { fg = "#b5e4f4" }
rest = { fg = "#6d1610" }

separator_style = { fg = "#807d7b" }

[notify]
title_info = { fg = "#b5e4f4" }
title_warn = { fg = "#807d7c" }
title_error = { fg = "#db2d20" }

[filetype]
rules = [
  { mime = "image/*", fg = "#807d7c" },
  { mime = "{audio, video}/*", fg = "#01a252" },

  { mime = "application/{pdf,doc,rtf}", fg = "#928f8e" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#b5e4f4" },
  { mime = "inode/directory", is = "link", fg = "#b5e4f4" },
  { mime = "*", is = "sock", fg = "#807d7b" },
  { mime = "*", is = "char", fg = "#fded02" },
  { mime = "*", is = "exec", fg = "#01a252" },
  { mime = "*", fg = "#928f8e" },
  { mime = "inode/directory", fg = "#01a0e4" },
]
