# vim: ft=toml
[mgr]
cwd = { fg = "#00a6b2" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#0000ff" }
find_position = { fg = "#b200b2" }

marker_copied = { fg = "#00a600", bg = "#00a600" }
marker_cut = { fg = "#990000", bg = "#990000" }
marker_selected = { fg = "#0000ff", bg = "#0000ff" }

tab_inactive = { fg = "#a8a8a8" }
tab_active = { fg = "#000000", bg = "#a8a8a8" }

count_copied = { fg = "#000000", bg = "#00a600" }
count_cut = { fg = "#000000", bg = "#990000" }
count_selected = { fg = "#000000", bg = "#0000ff" }

border_style = { fg = "#1f08db" }

[mode]
normal_main = { fg = "#000000", bg = "#1f08db", bold = true }
normal_alt = { fg = "#1f08db", bg = "#666666" }

select_alt = { fg = "#b200b2", bg = "#666666" }
select_main = { fg = "#000000", bg = "#b200b2", bold = true }

unset_main = { fg = "#000000", bg = "#990000", bold = true }
unset_alt = { fg = "#990000", bg = "#666666" }

[status]
perm_exec = { fg = "#00a600" }
perm_read = { fg = "#0000ff" }
perm_sep = { fg = "#00a6b2" }
perm_type = { fg = "#1f08db" }
perm_write = { fg = "#990000" }

progress_error = { fg = "#990000", bg = "#000000" }
progress_label = { fg = "#a8a8a8", bg = "#000000" }
progress_normal = { fg = "#a8a8a8", bg = "#000000" }

[pick]
active = { fg = "#b200b2" }
border = { fg = "#1f08db" }
inactive = { fg = "#a8a8a8" }

[task]
title = { fg = "#1f08db" }
border = { fg = "#1f08db" }
hovered = { fg = "#a8a8a8", bg = "#666666" }

[input]
border = { fg = "#1f08db" }
selected = { bg = "#666666" }

[help]
desc = { fg = "#a8a8a8" }
on = { fg = "#00a6b2" }
run = { fg = "#b200b2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#666666", bg = "#a8a8a8" }

[which]
mask = { bg = "#666666" }
desc = { fg = "#a8a8a8" }
cand = { fg = "#00a6b2" }
rest = { fg = "#4c0000" }

separator_style = { fg = "#929292" }

[notify]
title_info = { fg = "#00a6b2" }
title_warn = { fg = "#0000ff" }
title_error = { fg = "#990000" }

[filetype]
rules = [
  { mime = "image/*", fg = "#0000ff" },
  { mime = "{audio, video}/*", fg = "#00a600" },

  { mime = "application/{pdf,doc,rtf}", fg = "#a8a8a8" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#00a6b2" },
  { mime = "inode/directory", is = "link", fg = "#00a6b2" },
  { mime = "*", is = "sock", fg = "#929292" },
  { mime = "*", is = "char", fg = "#999900" },
  { mime = "*", is = "exec", fg = "#00a600" },
  { mime = "*", fg = "#a8a8a8" },
  { mime = "inode/directory", fg = "#1f08db" },
]
