# vim: ft=toml
[mgr]
cwd = { fg = "#00d9df" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#62cae7" }
find_position = { fg = "#ce6fda" }

marker_copied = { fg = "#03f622", bg = "#03f622" }
marker_cut = { fg = "#bb0000", bg = "#bb0000" }
marker_selected = { fg = "#62cae7", bg = "#62cae7" }

tab_inactive = { fg = "#a1a1a1" }
tab_active = { fg = "#171717", bg = "#a1a1a1" }

count_copied = { fg = "#171717", bg = "#03f622" }
count_cut = { fg = "#171717", bg = "#bb0000" }
count_selected = { fg = "#171717", bg = "#62cae7" }

border_style = { fg = "#63d0f0" }

[mode]
normal_main = { fg = "#171717", bg = "#63d0f0", bold = true }
normal_alt = { fg = "#63d0f0", bg = "#555555" }

select_alt = { fg = "#ce6fda", bg = "#555555" }
select_main = { fg = "#171717", bg = "#ce6fda", bold = true }

unset_main = { fg = "#171717", bg = "#bb0000", bold = true }
unset_alt = { fg = "#bb0000", bg = "#555555" }

[status]
perm_exec = { fg = "#03f622" }
perm_read = { fg = "#62cae7" }
perm_sep = { fg = "#00d9df" }
perm_type = { fg = "#63d0f0" }
perm_write = { fg = "#bb0000" }

progress_error = { fg = "#bb0000", bg = "#171717" }
progress_label = { fg = "#a1a1a1", bg = "#171717" }
progress_normal = { fg = "#a1a1a1", bg = "#171717" }

[pick]
active = { fg = "#ce6fda" }
border = { fg = "#63d0f0" }
inactive = { fg = "#a1a1a1" }

[task]
title = { fg = "#63d0f0" }
border = { fg = "#63d0f0" }
hovered = { fg = "#a1a1a1", bg = "#555555" }

[input]
border = { fg = "#63d0f0" }
selected = { bg = "#555555" }

[help]
desc = { fg = "#a1a1a1" }
on = { fg = "#00d9df" }
run = { fg = "#ce6fda" }
hovered = { reversed = true, bold = true }
footer = { fg = "#555555", bg = "#a1a1a1" }

[which]
mask = { bg = "#555555" }
desc = { fg = "#a1a1a1" }
cand = { fg = "#00d9df" }
rest = { fg = "#5d0000" }

separator_style = { fg = "#888888" }

[notify]
title_info = { fg = "#00d9df" }
title_warn = { fg = "#62cae7" }
title_error = { fg = "#bb0000" }

[filetype]
rules = [
  { mime = "image/*", fg = "#62cae7" },
  { mime = "{audio, video}/*", fg = "#03f622" },

  { mime = "application/{pdf,doc,rtf}", fg = "#a1a1a1" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#00d9df" },
  { mime = "inode/directory", is = "link", fg = "#00d9df" },
  { mime = "*", is = "sock", fg = "#888888" },
  { mime = "*", is = "char", fg = "#f2f067" },
  { mime = "*", is = "exec", fg = "#03f622" },
  { mime = "*", fg = "#a1a1a1" },
  { mime = "inode/directory", fg = "#63d0f0" },
]
