# vim: ft=toml
[mgr]
cwd = { fg = "#0184bc" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#febb2a" }
find_position = { fg = "#a626a4" }

marker_copied = { fg = "#50a14f", bg = "#50a14f" }
marker_cut = { fg = "#ca1243", bg = "#ca1243" }
marker_selected = { fg = "#febb2a", bg = "#febb2a" }

tab_inactive = { fg = "#383a42" }
tab_active = { fg = "#e7e7e9", bg = "#383a42" }

count_copied = { fg = "#e7e7e9", bg = "#50a14f" }
count_cut = { fg = "#e7e7e9", bg = "#ca1243" }
count_selected = { fg = "#e7e7e9", bg = "#febb2a" }

border_style = { fg = "#4078f2" }

[mode]
normal_main = { fg = "#e7e7e9", bg = "#4078f2", bold = true }
normal_alt = { fg = "#4078f2", bg = "#cacace" }

select_alt = { fg = "#a626a4", bg = "#cacace" }
select_main = { fg = "#e7e7e9", bg = "#a626a4", bold = true }

unset_main = { fg = "#e7e7e9", bg = "#ca1243", bold = true }
unset_alt = { fg = "#ca1243", bg = "#cacace" }

[status]
perm_exec = { fg = "#50a14f" }
perm_read = { fg = "#febb2a" }
perm_sep = { fg = "#0184bc" }
perm_type = { fg = "#4078f2" }
perm_write = { fg = "#ca1243" }

progress_error = { fg = "#ca1243", bg = "#e7e7e9" }
progress_label = { fg = "#383a42", bg = "#e7e7e9" }
progress_normal = { fg = "#383a42", bg = "#e7e7e9" }

[pick]
active = { fg = "#a626a4" }
border = { fg = "#4078f2" }
inactive = { fg = "#383a42" }

[task]
title = { fg = "#4078f2" }
border = { fg = "#4078f2" }
hovered = { fg = "#383a42", bg = "#cacace" }

[input]
border = { fg = "#4078f2" }
selected = { bg = "#cacace" }

[help]
desc = { fg = "#383a42" }
on = { fg = "#0184bc" }
run = { fg = "#a626a4" }
hovered = { reversed = true, bold = true }
footer = { fg = "#cacace", bg = "#383a42" }

[which]
mask = { bg = "#cacace" }
desc = { fg = "#383a42" }
cand = { fg = "#0184bc" }
rest = { fg = "#986801" }

separator_style = { fg = "#696c77" }

[notify]
title_info = { fg = "#0184bc" }
title_warn = { fg = "#febb2a" }
title_error = { fg = "#ca1243" }

[filetype]
rules = [
  { mime = "image/*", fg = "#febb2a" },
  { mime = "{audio, video}/*", fg = "#50a14f" },

  { mime = "application/{pdf,doc,rtf}", fg = "#383a42" },

  { mime = "application/" },

  { mime = "inode/directory", fg = "#4078f2" },
  { mime = "*", is = "link", fg = "#0184bc" },
  { mime = "*/", is = "link", fg = "#0184bc" },
  { mime = "*", is = "sock", fg = "#696c77" },
  { mime = "*", is = "char", fg = "#c18401" },
  { mime = "*", is = "exec", fg = "#50a14f" },
  { mime = "*", fg = "#383a42" },
]
