# vim: ft=toml
[mgr]
cwd = { fg = "#4b73a2" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#006fc0" }
find_position = { fg = "#d75cff" }

marker_copied = { fg = "#5eb83c", bg = "#5eb83c" }
marker_cut = { fg = "#e63853", bg = "#e63853" }
marker_selected = { fg = "#006fc0", bg = "#006fc0" }

tab_inactive = { fg = "#a5acae" }
tab_active = { fg = "#0e1011", bg = "#a5acae" }

count_copied = { fg = "#0e1011", bg = "#5eb83c" }
count_cut = { fg = "#0e1011", bg = "#e63853" }
count_selected = { fg = "#0e1011", bg = "#006fc0" }

border_style = { fg = "#359ddf" }

[mode]
normal_main = { fg = "#0e1011", bg = "#359ddf", bold = true }
normal_alt = { fg = "#359ddf", bg = "#001e26" }

select_alt = { fg = "#d75cff", bg = "#001e26" }
select_main = { fg = "#0e1011", bg = "#d75cff", bold = true }

unset_main = { fg = "#0e1011", bg = "#e63853", bold = true }
unset_alt = { fg = "#e63853", bg = "#001e26" }

[status]
perm_exec = { fg = "#5eb83c" }
perm_read = { fg = "#006fc0" }
perm_sep = { fg = "#4b73a2" }
perm_type = { fg = "#359ddf" }
perm_write = { fg = "#e63853" }

progress_error = { fg = "#e63853", bg = "#0e1011" }
progress_label = { fg = "#a5acae", bg = "#0e1011" }
progress_normal = { fg = "#a5acae", bg = "#0e1011" }

[pick]
active = { fg = "#d75cff" }
border = { fg = "#359ddf" }
inactive = { fg = "#a5acae" }

[task]
title = { fg = "#359ddf" }
border = { fg = "#359ddf" }
hovered = { fg = "#a5acae", bg = "#001e26" }

[input]
border = { fg = "#359ddf" }
selected = { bg = "#001e26" }

[help]
desc = { fg = "#a5acae" }
on = { fg = "#4b73a2" }
run = { fg = "#d75cff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#001e26", bg = "#a5acae" }

[which]
mask = { bg = "#001e26" }
desc = { fg = "#a5acae" }
cand = { fg = "#4b73a2" }
rest = { fg = "#731c29" }

separator_style = { fg = "#6e7d81" }

[notify]
title_info = { fg = "#4b73a2" }
title_warn = { fg = "#006fc0" }
title_error = { fg = "#e63853" }

[filetype]
rules = [
  { mime = "image/*", fg = "#006fc0" },
  { mime = "{audio, video}/*", fg = "#5eb83c" },

  { mime = "application/{pdf,doc,rtf}", fg = "#a5acae" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#4b73a2" },
  { mime = "inode/directory", is = "link", fg = "#4b73a2" },
  { mime = "inode/directory", fg = "#359ddf" },
  { mime = "*", is = "sock", fg = "#6e7d81" },
  { mime = "*", is = "char", fg = "#a57705" },
  { mime = "*", is = "exec", fg = "#5eb83c" },
  { mime = "*", fg = "#a5acae" },
]
