# vim: ft=toml
[mgr]
cwd = { fg = "#8be9fd" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#f1fa8c" }
find_position = { fg = "#ff79c6" }

marker_copied = { fg = "#50fa7b", bg = "#50fa7b" }
marker_cut = { fg = "#ff5555", bg = "#ff5555" }
marker_selected = { fg = "#f1fa8c", bg = "#f1fa8c" }

tab_inactive = { fg = "#f8f8f2" }
tab_active = { fg = "#282a36", bg = "#f8f8f2" }

count_copied = { fg = "#282a36", bg = "#50fa7b" }
count_cut = { fg = "#282a36", bg = "#ff5555" }
count_selected = { fg = "#282a36", bg = "#f1fa8c" }

border_style = { fg = "#bd93f9" }

[mode]
normal_main = { fg = "#282a36", bg = "#bd93f9", bold = true }
normal_alt = { fg = "#bd93f9", bg = "#44475a" }

select_alt = { fg = "#ff79c6", bg = "#44475a" }
select_main = { fg = "#282a36", bg = "#ff79c6", bold = true }

unset_main = { fg = "#282a36", bg = "#ff5555", bold = true }
unset_alt = { fg = "#ff5555", bg = "#44475a" }

[status]
perm_exec = { fg = "#50fa7b" }
perm_read = { fg = "#f1fa8c" }
perm_sep = { fg = "#8be9fd" }
perm_type = { fg = "#bd93f9" }
perm_write = { fg = "#ff5555" }

progress_error = { fg = "#ff5555", bg = "#282a36" }
progress_label = { fg = "#f8f8f2", bg = "#282a36" }
progress_normal = { fg = "#f8f8f2", bg = "#282a36" }

[pick]
active = { fg = "#ff79c6" }
border = { fg = "#bd93f9" }
inactive = { fg = "#f8f8f2" }

[task]
title = { fg = "#bd93f9" }
border = { fg = "#bd93f9" }
hovered = { fg = "#f8f8f2", bg = "#44475a" }

[input]
border = { fg = "#bd93f9" }
selected = { bg = "#44475a" }

[help]
desc = { fg = "#f8f8f2" }
on = { fg = "#8be9fd" }
run = { fg = "#ff79c6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#44475a", bg = "#f8f8f2" }

[which]
mask = { bg = "#44475a" }
desc = { fg = "#f8f8f2" }
cand = { fg = "#8be9fd" }
rest = { fg = "#ffb86c" }

separator_style = { fg = "#9ea8c7" }

[notify]
title_info = { fg = "#8be9fd" }
title_warn = { fg = "#f1fa8c" }
title_error = { fg = "#ff5555" }

[filetype]
rules = [
  { mime = "image/*", fg = "#f1fa8c" },
  { mime = "{audio, video}/*", fg = "#50fa7b" },

  { mime = "application/{pdf,doc,rtf}", fg = "#f8f8f2" },

  { mime = "application/" },

  { mime = "inode/directory", fg = "#bd93f9" },
  { mime = "*", is = "link", fg = "#8be9fd" },
  { mime = "*/", is = "link", fg = "#8be9fd" },
  { mime = "*", is = "sock", fg = "#9ea8c7" },
  { mime = "*", is = "char", fg = "#ffb86c" },
  { mime = "*", is = "exec", fg = "#50fa7b" },
  { mime = "*", fg = "#f8f8f2" },
]
