# vim: ft=toml
[mgr]
cwd = { fg = "#42bda7" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#cfa546" }
find_position = { fg = "#b799ff" }

marker_copied = { fg = "#95b659", bg = "#95b659" }
marker_cut = { fg = "#ff8782", bg = "#ff8782" }
marker_selected = { fg = "#cfa546", bg = "#cfa546" }

tab_inactive = { fg = "#bab9b6" }
tab_active = { fg = "#23262b", bg = "#bab9b6" }

count_copied = { fg = "#23262b", bg = "#95b659" }
count_cut = { fg = "#23262b", bg = "#ff8782" }
count_selected = { fg = "#23262b", bg = "#cfa546" }

border_style = { fg = "#66b0ef" }

[mode]
normal_main = { fg = "#23262b", bg = "#66b0ef", bold = true }
normal_alt = { fg = "#66b0ef", bg = "#3e4044" }

select_alt = { fg = "#b799ff", bg = "#3e4044" }
select_main = { fg = "#23262b", bg = "#b799ff", bold = true }

unset_main = { fg = "#23262b", bg = "#ff8782", bold = true }
unset_alt = { fg = "#ff8782", bg = "#3e4044" }

[status]
perm_exec = { fg = "#95b659" }
perm_read = { fg = "#cfa546" }
perm_sep = { fg = "#42bda7" }
perm_type = { fg = "#66b0ef" }
perm_write = { fg = "#ff8782" }

progress_error = { fg = "#ff8782", bg = "#23262b" }
progress_label = { fg = "#bab9b6", bg = "#23262b" }
progress_normal = { fg = "#bab9b6", bg = "#23262b" }

[pick]
active = { fg = "#b799ff" }
border = { fg = "#66b0ef" }
inactive = { fg = "#bab9b6" }

[task]
title = { fg = "#66b0ef" }
border = { fg = "#66b0ef" }
hovered = { fg = "#bab9b6", bg = "#3e4044" }

[input]
border = { fg = "#66b0ef" }
selected = { bg = "#3e4044" }

[help]
desc = { fg = "#bab9b6" }
on = { fg = "#42bda7" }
run = { fg = "#b799ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3e4044", bg = "#bab9b6" }

[which]
mask = { bg = "#3e4044" }
desc = { fg = "#bab9b6" }
cand = { fg = "#42bda7" }
rest = { fg = "#f382d8" }

separator_style = { fg = "#abaaa8" }

[notify]
title_info = { fg = "#42bda7" }
title_warn = { fg = "#cfa546" }
title_error = { fg = "#ff8782" }

[filetype]
rules = [
  { mime = "image/*", fg = "#cfa546" },
  { mime = "{audio, video}/*", fg = "#95b659" },

  { mime = "application/{pdf,doc,rtf}", fg = "#bab9b6" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#42bda7" },
  { mime = "inode/directory", is = "link", fg = "#42bda7" },
  { mime = "inode/directory", fg = "#66b0ef" },
  { mime = "*", is = "sock", fg = "#abaaa8" },
  { mime = "*", is = "char", fg = "#e99857" },
  { mime = "*", is = "exec", fg = "#95b659" },
  { mime = "*", fg = "#bab9b6" },
]
