# vim: ft=toml
[mgr]
cwd = { fg = "#b0c4de" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#87ceeb" }
find_position = { fg = "#deb887" }

marker_copied = { fg = "#86af80", bg = "#86af80" }
marker_cut = { fg = "#cd5c5c", bg = "#cd5c5c" }
marker_selected = { fg = "#87ceeb", bg = "#87ceeb" }

tab_inactive = { fg = "#a19083" }
tab_active = { fg = "#1c1c1c", bg = "#a19083" }

count_copied = { fg = "#1c1c1c", bg = "#86af80" }
count_cut = { fg = "#1c1c1c", bg = "#cd5c5c" }
count_selected = { fg = "#1c1c1c", bg = "#87ceeb" }

border_style = { fg = "#6495ed" }

[mode]
normal_main = { fg = "#1c1c1c", bg = "#6495ed", bold = true }
normal_alt = { fg = "#6495ed", bg = "#554444" }

select_alt = { fg = "#deb887", bg = "#554444" }
select_main = { fg = "#1c1c1c", bg = "#deb887", bold = true }

unset_main = { fg = "#1c1c1c", bg = "#cd5c5c", bold = true }
unset_alt = { fg = "#cd5c5c", bg = "#554444" }

[status]
perm_exec = { fg = "#86af80" }
perm_read = { fg = "#87ceeb" }
perm_sep = { fg = "#b0c4de" }
perm_type = { fg = "#6495ed" }
perm_write = { fg = "#cd5c5c" }

progress_error = { fg = "#cd5c5c", bg = "#1c1c1c" }
progress_label = { fg = "#a19083", bg = "#1c1c1c" }
progress_normal = { fg = "#a19083", bg = "#1c1c1c" }

[pick]
active = { fg = "#deb887" }
border = { fg = "#6495ed" }
inactive = { fg = "#a19083" }

[task]
title = { fg = "#6495ed" }
border = { fg = "#6495ed" }
hovered = { fg = "#a19083", bg = "#554444" }

[input]
border = { fg = "#6495ed" }
selected = { bg = "#554444" }

[help]
desc = { fg = "#a19083" }
on = { fg = "#b0c4de" }
run = { fg = "#deb887" }
hovered = { reversed = true, bold = true }
footer = { fg = "#554444", bg = "#a19083" }

[which]
mask = { bg = "#554444" }
desc = { fg = "#a19083" }
cand = { fg = "#b0c4de" }
rest = { fg = "#662e2e" }

separator_style = { fg = "#88776e" }

[notify]
title_info = { fg = "#b0c4de" }
title_warn = { fg = "#87ceeb" }
title_error = { fg = "#cd5c5c" }

[filetype]
rules = [
  { mime = "image/*", fg = "#87ceeb" },
  { mime = "{audio, video}/*", fg = "#86af80" },

  { mime = "application/{pdf,doc,rtf}", fg = "#a19083" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#b0c4de" },
  { mime = "inode/directory", is = "link", fg = "#b0c4de" },
  { mime = "*", is = "sock", fg = "#88776e" },
  { mime = "*", is = "char", fg = "#e8ae5b" },
  { mime = "*", is = "exec", fg = "#86af80" },
  { mime = "*", fg = "#a19083" },
  { mime = "inode/directory", fg = "#6495ed" },
]
