# vim: ft=toml
[mgr]
cwd = { fg = "#20a5ba" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#20bbfc" }
find_position = { fg = "#523c79" }

marker_copied = { fg = "#10a778", bg = "#10a778" }
marker_cut = { fg = "#c30771", bg = "#c30771" }
marker_selected = { fg = "#20bbfc", bg = "#20bbfc" }

tab_inactive = { fg = "#b3b3b3" }
tab_active = { fg = "#212121", bg = "#b3b3b3" }

count_copied = { fg = "#212121", bg = "#10a778" }
count_cut = { fg = "#212121", bg = "#c30771" }
count_selected = { fg = "#212121", bg = "#20bbfc" }

border_style = { fg = "#008ec4" }

[mode]
normal_main = { fg = "#212121", bg = "#008ec4", bold = true }
normal_alt = { fg = "#008ec4", bg = "#424242" }

select_alt = { fg = "#523c79", bg = "#424242" }
select_main = { fg = "#212121", bg = "#523c79", bold = true }

unset_main = { fg = "#212121", bg = "#c30771", bold = true }
unset_alt = { fg = "#c30771", bg = "#424242" }

[status]
perm_exec = { fg = "#10a778" }
perm_read = { fg = "#20bbfc" }
perm_sep = { fg = "#20a5ba" }
perm_type = { fg = "#008ec4" }
perm_write = { fg = "#c30771" }

progress_error = { fg = "#c30771", bg = "#212121" }
progress_label = { fg = "#b3b3b3", bg = "#212121" }
progress_normal = { fg = "#b3b3b3", bg = "#212121" }

[pick]
active = { fg = "#523c79" }
border = { fg = "#008ec4" }
inactive = { fg = "#b3b3b3" }

[task]
title = { fg = "#008ec4" }
border = { fg = "#008ec4" }
hovered = { fg = "#b3b3b3", bg = "#424242" }

[input]
border = { fg = "#008ec4" }
selected = { bg = "#424242" }

[help]
desc = { fg = "#b3b3b3" }
on = { fg = "#20a5ba" }
run = { fg = "#523c79" }
hovered = { reversed = true, bold = true }
footer = { fg = "#424242", bg = "#b3b3b3" }

[which]
mask = { bg = "#424242" }
desc = { fg = "#b3b3b3" }
cand = { fg = "#20a5ba" }
rest = { fg = "#610338" }

separator_style = { fg = "#8d8d8d" }

[notify]
title_info = { fg = "#20a5ba" }
title_warn = { fg = "#20bbfc" }
title_error = { fg = "#c30771" }

[filetype]
rules = [
  { mime = "image/*", fg = "#20bbfc" },
  { mime = "{audio, video}/*", fg = "#10a778" },

  { mime = "application/{pdf,doc,rtf}", fg = "#b3b3b3" },

  { mime = "application/" },

  { mime = "inode/directory", fg = "#008ec4" },
  { mime = "*", is = "link", fg = "#20a5ba" },
  { mime = "*/", is = "link", fg = "#20a5ba" },
  { mime = "*", is = "sock", fg = "#8d8d8d" },
  { mime = "*", is = "char", fg = "#a89c14" },
  { mime = "*", is = "exec", fg = "#10a778" },
  { mime = "*", fg = "#b3b3b3" },
]
