# vim: ft=toml
[mgr]
cwd = { fg = "#95e6cb" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#ffb454" }
find_position = { fg = "#d2a6ff" }

marker_copied = { fg = "#aad94c", bg = "#aad94c" }
marker_cut = { fg = "#f07178", bg = "#f07178" }
marker_selected = { fg = "#ffb454", bg = "#ffb454" }

tab_inactive = { fg = "#e6e1cf" }
tab_active = { fg = "#0b0e14", bg = "#e6e1cf" }

count_copied = { fg = "#0b0e14", bg = "#aad94c" }
count_cut = { fg = "#0b0e14", bg = "#f07178" }
count_selected = { fg = "#0b0e14", bg = "#ffb454" }

border_style = { fg = "#59c2ff" }

[mode]
normal_main = { fg = "#0b0e14", bg = "#59c2ff", bold = true }
normal_alt = { fg = "#59c2ff", bg = "#202229" }

select_alt = { fg = "#d2a6ff", bg = "#202229" }
select_main = { fg = "#0b0e14", bg = "#d2a6ff", bold = true }

unset_main = { fg = "#0b0e14", bg = "#f07178", bold = true }
unset_alt = { fg = "#f07178", bg = "#202229" }

[status]
perm_exec = { fg = "#aad94c" }
perm_read = { fg = "#ffb454" }
perm_sep = { fg = "#95e6cb" }
perm_type = { fg = "#59c2ff" }
perm_write = { fg = "#f07178" }

progress_error = { fg = "#f07178", bg = "#0b0e14" }
progress_label = { fg = "#e6e1cf", bg = "#0b0e14" }
progress_normal = { fg = "#e6e1cf", bg = "#0b0e14" }

[pick]
active = { fg = "#d2a6ff" }
border = { fg = "#59c2ff" }
inactive = { fg = "#e6e1cf" }

[task]
title = { fg = "#59c2ff" }
border = { fg = "#59c2ff" }
hovered = { fg = "#e6e1cf", bg = "#202229" }

[input]
border = { fg = "#59c2ff" }
selected = { bg = "#202229" }

[help]
desc = { fg = "#e6e1cf" }
on = { fg = "#95e6cb" }
run = { fg = "#d2a6ff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#202229", bg = "#e6e1cf" }

[which]
mask = { bg = "#202229" }
desc = { fg = "#e6e1cf" }
cand = { fg = "#95e6cb" }
rest = { fg = "#e6b450" }

separator_style = { fg = "#bfbdb6" }

[notify]
title_info = { fg = "#95e6cb" }
title_warn = { fg = "#ffb454" }
title_error = { fg = "#f07178" }

[filetype]
rules = [
  { mime = "image/*", fg = "#ffb454" },
  { mime = "{audio, video}/*", fg = "#aad94c" },

  { mime = "application/{pdf,doc,rtf}", fg = "#e6e1cf" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#95e6cb" },
  { mime = "inode/directory", is = "link", fg = "#95e6cb" },
  { mime = "*", is = "sock", fg = "#bfbdb6" },
  { mime = "*", is = "char", fg = "#ff8f40" },
  { mime = "*", is = "exec", fg = "#aad94c" },
  { mime = "*", fg = "#e6e1cf" },
  { mime = "inode/directory", fg = "#59c2ff" },
]
