# vim: ft=toml
[mgr]
cwd = { fg = "#389aac" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#135879" }
find_position = { fg = "#a57fc4" }

marker_copied = { fg = "#7bb75b", bg = "#7bb75b" }
marker_cut = { fg = "#ce3e60", bg = "#ce3e60" }
marker_selected = { fg = "#135879", bg = "#135879" }

tab_inactive = { fg = "#d0d2ce" }
tab_active = { fg = "#1d1d1d", bg = "#d0d2ce" }

count_copied = { fg = "#1d1d1d", bg = "#7bb75b" }
count_cut = { fg = "#1d1d1d", bg = "#ce3e60" }
count_selected = { fg = "#1d1d1d", bg = "#135879" }

border_style = { fg = "#4c99d3" }

[mode]
normal_main = { fg = "#1d1d1d", bg = "#4c99d3", bold = true }
normal_alt = { fg = "#4c99d3", bg = "#585a58" }

select_alt = { fg = "#a57fc4", bg = "#585a58" }
select_main = { fg = "#1d1d1d", bg = "#a57fc4", bold = true }

unset_main = { fg = "#1d1d1d", bg = "#ce3e60", bold = true }
unset_alt = { fg = "#ce3e60", bg = "#585a58" }

[status]
perm_exec = { fg = "#7bb75b" }
perm_read = { fg = "#135879" }
perm_sep = { fg = "#389aac" }
perm_type = { fg = "#4c99d3" }
perm_write = { fg = "#ce3e60" }

progress_error = { fg = "#ce3e60", bg = "#1d1d1d" }
progress_label = { fg = "#d0d2ce", bg = "#1d1d1d" }
progress_normal = { fg = "#d0d2ce", bg = "#1d1d1d" }

[pick]
active = { fg = "#a57fc4" }
border = { fg = "#4c99d3" }
inactive = { fg = "#d0d2ce" }

[task]
title = { fg = "#4c99d3" }
border = { fg = "#4c99d3" }
hovered = { fg = "#d0d2ce", bg = "#585a58" }

[input]
border = { fg = "#4c99d3" }
selected = { bg = "#585a58" }

[help]
desc = { fg = "#d0d2ce" }
on = { fg = "#389aac" }
run = { fg = "#a57fc4" }
hovered = { reversed = true, bold = true }
footer = { fg = "#585a58", bg = "#d0d2ce" }

[which]
mask = { bg = "#585a58" }
desc = { fg = "#d0d2ce" }
cand = { fg = "#389aac" }
rest = { fg = "#671f30" }

separator_style = { fg = "#a8aaa7" }

[notify]
title_info = { fg = "#389aac" }
title_warn = { fg = "#135879" }
title_error = { fg = "#ce3e60" }

[filetype]
rules = [
  { mime = "image/*", fg = "#135879" },
  { mime = "{audio, video}/*", fg = "#7bb75b" },

  { mime = "application/{pdf,doc,rtf}", fg = "#d0d2ce" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#389aac" },
  { mime = "inode/directory", is = "link", fg = "#389aac" },
  { mime = "inode/directory", fg = "#4c99d3" },
  { mime = "*", is = "sock", fg = "#a8aaa7" },
  { mime = "*", is = "char", fg = "#e8b32a" },
  { mime = "*", is = "exec", fg = "#7bb75b" },
  { mime = "*", fg = "#d0d2ce" },
]
