# vim: ft=toml
[mgr]
cwd = { fg = "#23d7d7" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#23d7d7" }
find_position = { fg = "#9413e5" }

marker_copied = { fg = "#74af68", bg = "#74af68" }
marker_cut = { fg = "#ff4242", bg = "#ff4242" }
marker_selected = { fg = "#23d7d7", bg = "#23d7d7" }

tab_inactive = { fg = "#b8beba" }
tab_active = { fg = "#131d42", bg = "#b8beba" }

count_copied = { fg = "#131d42", bg = "#74af68" }
count_cut = { fg = "#131d42", bg = "#ff4242" }
count_selected = { fg = "#131d42", bg = "#23d7d7" }

border_style = { fg = "#338f86" }

[mode]
normal_main = { fg = "#131d42", bg = "#338f86", bold = true }
normal_alt = { fg = "#338f86", bg = "#3e5548" }

select_alt = { fg = "#9413e5", bg = "#3e5548" }
select_main = { fg = "#131d42", bg = "#9413e5", bold = true }

unset_main = { fg = "#131d42", bg = "#ff4242", bold = true }
unset_alt = { fg = "#ff4242", bg = "#3e5548" }

[status]
perm_exec = { fg = "#74af68" }
perm_read = { fg = "#23d7d7" }
perm_sep = { fg = "#23d7d7" }
perm_type = { fg = "#338f86" }
perm_write = { fg = "#ff4242" }

progress_error = { fg = "#ff4242", bg = "#131d42" }
progress_label = { fg = "#b8beba", bg = "#131d42" }
progress_normal = { fg = "#b8beba", bg = "#131d42" }

[pick]
active = { fg = "#9413e5" }
border = { fg = "#338f86" }
inactive = { fg = "#b8beba" }

[task]
title = { fg = "#338f86" }
border = { fg = "#338f86" }
hovered = { fg = "#b8beba", bg = "#3e5548" }

[input]
border = { fg = "#338f86" }
selected = { bg = "#3e5548" }

[help]
desc = { fg = "#b8beba" }
on = { fg = "#23d7d7" }
run = { fg = "#9413e5" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3e5548", bg = "#b8beba" }

[which]
mask = { bg = "#3e5548" }
desc = { fg = "#b8beba" }
cand = { fg = "#23d7d7" }
rest = { fg = "#7f2121" }

separator_style = { fg = "#8f9b94" }

[notify]
title_info = { fg = "#23d7d7" }
title_warn = { fg = "#23d7d7" }
title_error = { fg = "#ff4242" }

[filetype]
rules = [
  { mime = "image/*", fg = "#23d7d7" },
  { mime = "{audio, video}/*", fg = "#74af68" },

  { mime = "application/{pdf,doc,rtf}", fg = "#b8beba" },

  { mime = "application/" },

  { mime = "inode/directory", fg = "#338f86" },
  { mime = "*", is = "link", fg = "#23d7d7" },
  { mime = "*/", is = "link", fg = "#23d7d7" },
  { mime = "*", is = "sock", fg = "#8f9b94" },
  { mime = "*", is = "char", fg = "#ffad29" },
  { mime = "*", is = "exec", fg = "#74af68" },
  { mime = "*", fg = "#b8beba" },
]
