# vim: ft=toml
[mgr]
cwd = { fg = "#b3f4f3" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#ebde76" }
find_position = { fg = "#ff79c6" }

marker_copied = { fg = "#b1f2a7", bg = "#b1f2a7" }
marker_cut = { fg = "#e965a5", bg = "#e965a5" }
marker_selected = { fg = "#ebde76", bg = "#ebde76" }

tab_inactive = { fg = "#e4dee9" }
tab_active = { fg = "#211e2a", bg = "#e4dee9" }

count_copied = { fg = "#211e2a", bg = "#b1f2a7" }
count_cut = { fg = "#211e2a", bg = "#e965a5" }
count_selected = { fg = "#211e2a", bg = "#ebde76" }

border_style = { fg = "#95a6f4" }

[mode]
normal_main = { fg = "#211e2a", bg = "#95a6f4", bold = true }
normal_alt = { fg = "#95a6f4", bg = "#3f3951" }

select_alt = { fg = "#ff79c6", bg = "#3f3951" }
select_main = { fg = "#211e2a", bg = "#ff79c6", bold = true }

unset_main = { fg = "#211e2a", bg = "#e965a5", bold = true }
unset_alt = { fg = "#e965a5", bg = "#3f3951" }

[status]
perm_exec = { fg = "#b1f2a7" }
perm_read = { fg = "#ebde76" }
perm_sep = { fg = "#b3f4f3" }
perm_type = { fg = "#95a6f4" }
perm_write = { fg = "#e965a5" }

progress_error = { fg = "#e965a5", bg = "#211e2a" }
progress_label = { fg = "#e4dee9", bg = "#211e2a" }
progress_normal = { fg = "#e4dee9", bg = "#211e2a" }

[pick]
active = { fg = "#ff79c6" }
border = { fg = "#95a6f4" }
inactive = { fg = "#e4dee9" }

[task]
title = { fg = "#95a6f4" }
border = { fg = "#95a6f4" }
hovered = { fg = "#e4dee9", bg = "#3f3951" }

[input]
border = { fg = "#95a6f4" }
selected = { bg = "#3f3951" }

[help]
desc = { fg = "#e4dee9" }
on = { fg = "#b3f4f3" }
run = { fg = "#ff79c6" }
hovered = { reversed = true, bold = true }
footer = { fg = "#3f3951", bg = "#e4dee9" }

[which]
mask = { bg = "#3f3951" }
desc = { fg = "#e4dee9" }
cand = { fg = "#b3f4f3" }
rest = { fg = "#bd93f9" }

separator_style = { fg = "#8a829e" }

[notify]
title_info = { fg = "#b3f4f3" }
title_warn = { fg = "#ebde76" }
title_error = { fg = "#e965a5" }

[filetype]
rules = [
  { mime = "image/*", fg = "#ebde76" },
  { mime = "{audio, video}/*", fg = "#b1f2a7" },

  { mime = "application/{pdf,doc,rtf}", fg = "#e4dee9" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#b3f4f3" },
  { mime = "inode/directory", is = "link", fg = "#b3f4f3" },
  { mime = "inode/directory", fg = "#95a6f4" },
  { mime = "*", is = "sock", fg = "#8a829e" },
  { mime = "*", is = "char", fg = "#f4b870" },
  { mime = "*", is = "exec", fg = "#b1f2a7" },
  { mime = "*", fg = "#e4dee9" },
]
