# vim: ft=toml
[mgr]
cwd = { fg = "#3255ff" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#1d4fff" }
find_position = { fg = "#2435db" }

marker_copied = { fg = "#e22828", bg = "#e22828" }
marker_cut = { fg = "#e60712", bg = "#e60712" }
marker_selected = { fg = "#1d4fff", bg = "#1d4fff" }

tab_inactive = { fg = "#d3d3cd" }
tab_active = { fg = "#1b1d1e", bg = "#d3d3cd" }

count_copied = { fg = "#1b1d1e", bg = "#e22828" }
count_cut = { fg = "#1b1d1e", bg = "#e60712" }
count_selected = { fg = "#1b1d1e", bg = "#1d4fff" }

border_style = { fg = "#2b3fff" }

[mode]
normal_main = { fg = "#1b1d1e", bg = "#2b3fff", bold = true }
normal_alt = { fg = "#2b3fff", bg = "#505354" }

select_alt = { fg = "#2435db", bg = "#505354" }
select_main = { fg = "#1b1d1e", bg = "#2435db", bold = true }

unset_main = { fg = "#1b1d1e", bg = "#e60712", bold = true }
unset_alt = { fg = "#e60712", bg = "#505354" }

[status]
perm_exec = { fg = "#e22828" }
perm_read = { fg = "#1d4fff" }
perm_sep = { fg = "#3255ff" }
perm_type = { fg = "#2b3fff" }
perm_write = { fg = "#e60712" }

progress_error = { fg = "#e60712", bg = "#1b1d1e" }
progress_label = { fg = "#d3d3cd", bg = "#1b1d1e" }
progress_normal = { fg = "#d3d3cd", bg = "#1b1d1e" }

[pick]
active = { fg = "#2435db" }
border = { fg = "#2b3fff" }
inactive = { fg = "#d3d3cd" }

[task]
title = { fg = "#2b3fff" }
border = { fg = "#2b3fff" }
hovered = { fg = "#d3d3cd", bg = "#505354" }

[input]
border = { fg = "#2b3fff" }
selected = { bg = "#505354" }

[help]
desc = { fg = "#d3d3cd" }
on = { fg = "#3255ff" }
run = { fg = "#2435db" }
hovered = { reversed = true, bold = true }
footer = { fg = "#505354", bg = "#d3d3cd" }

[which]
mask = { bg = "#505354" }
desc = { fg = "#d3d3cd" }
cand = { fg = "#3255ff" }
rest = { fg = "#730309" }

separator_style = { fg = "#a7a8a5" }

[notify]
title_info = { fg = "#3255ff" }
title_warn = { fg = "#1d4fff" }
title_error = { fg = "#e60712" }

[filetype]
rules = [
  { mime = "image/*", fg = "#1d4fff" },
  { mime = "{audio, video}/*", fg = "#e22828" },

  { mime = "application/{pdf,doc,rtf}", fg = "#d3d3cd" },

  { mime = "application/" },

  { mime = "inode/directory", fg = "#2b3fff" },
  { mime = "*", is = "link", fg = "#3255ff" },
  { mime = "*/", is = "link", fg = "#3255ff" },
  { mime = "*", is = "sock", fg = "#a7a8a5" },
  { mime = "*", is = "char", fg = "#e24655" },
  { mime = "*", is = "exec", fg = "#e22828" },
  { mime = "*", fg = "#d3d3cd" },
]
