# vim: ft=toml
[mgr]
cwd = { fg = "#3e999f" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#eab700" }
find_position = { fg = "#8959a8" }

marker_copied = { fg = "#718c00", bg = "#718c00" }
marker_cut = { fg = "#c82829", bg = "#c82829" }
marker_selected = { fg = "#eab700", bg = "#eab700" }

tab_inactive = { fg = "#373b41" }
tab_active = { fg = "#ffffff", bg = "#373b41" }

count_copied = { fg = "#ffffff", bg = "#718c00" }
count_cut = { fg = "#ffffff", bg = "#c82829" }
count_selected = { fg = "#ffffff", bg = "#eab700" }

border_style = { fg = "#4271ae" }

[mode]
normal_main = { fg = "#ffffff", bg = "#4271ae", bold = true }
normal_alt = { fg = "#4271ae", bg = "#c5c8c6" }

select_alt = { fg = "#8959a8", bg = "#c5c8c6" }
select_main = { fg = "#ffffff", bg = "#8959a8", bold = true }

unset_main = { fg = "#ffffff", bg = "#c82829", bold = true }
unset_alt = { fg = "#c82829", bg = "#c5c8c6" }

[status]
perm_exec = { fg = "#718c00" }
perm_read = { fg = "#eab700" }
perm_sep = { fg = "#3e999f" }
perm_type = { fg = "#4271ae" }
perm_write = { fg = "#c82829" }

progress_error = { fg = "#c82829", bg = "#ffffff" }
progress_label = { fg = "#373b41", bg = "#ffffff" }
progress_normal = { fg = "#373b41", bg = "#ffffff" }

[pick]
active = { fg = "#8959a8" }
border = { fg = "#4271ae" }
inactive = { fg = "#373b41" }

[task]
title = { fg = "#4271ae" }
border = { fg = "#4271ae" }
hovered = { fg = "#373b41", bg = "#c5c8c6" }

[input]
border = { fg = "#4271ae" }
selected = { bg = "#c5c8c6" }

[help]
desc = { fg = "#373b41" }
on = { fg = "#3e999f" }
run = { fg = "#8959a8" }
hovered = { reversed = true, bold = true }
footer = { fg = "#c5c8c6", bg = "#373b41" }

[which]
mask = { bg = "#c5c8c6" }
desc = { fg = "#373b41" }
cand = { fg = "#3e999f" }
rest = { fg = "#a3685a" }

separator_style = { fg = "#969896" }

[notify]
title_info = { fg = "#3e999f" }
title_warn = { fg = "#eab700" }
title_error = { fg = "#c82829" }

[filetype]
rules = [
  { mime = "image/*", fg = "#eab700" },
  { mime = "{audio, video}/*", fg = "#718c00" },

  { mime = "application/{pdf,doc,rtf}", fg = "#373b41" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#3e999f" },
  { mime = "inode/directory", is = "link", fg = "#3e999f" },
  { mime = "*", is = "sock", fg = "#969896" },
  { mime = "*", is = "char", fg = "#f5871f" },
  { mime = "*", is = "exec", fg = "#718c00" },
  { mime = "*", fg = "#373b41" },
  { mime = "inode/directory", fg = "#4271ae" },
]
