# vim: ft=toml
[mgr]
cwd = { fg = "#1e9ee6" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#589cf5" }
find_position = { fg = "#934d95" }

marker_copied = { fg = "#20af89", bg = "#20af89" }
marker_cut = { fg = "#f9555f", bg = "#f9555f" }
marker_selected = { fg = "#589cf5", bg = "#589cf5" }

tab_inactive = { fg = "#a1a1a1" }
tab_active = { fg = "#1c2836", bg = "#a1a1a1" }

count_copied = { fg = "#1c2836", bg = "#20af89" }
count_cut = { fg = "#1c2836", bg = "#f9555f" }
count_selected = { fg = "#1c2836", bg = "#589cf5" }

border_style = { fg = "#589cf5" }

[mode]
normal_main = { fg = "#1c2836", bg = "#589cf5", bold = true }
normal_alt = { fg = "#589cf5", bg = "#555555" }

select_alt = { fg = "#934d95", bg = "#555555" }
select_main = { fg = "#1c2836", bg = "#934d95", bold = true }

unset_main = { fg = "#1c2836", bg = "#f9555f", bold = true }
unset_alt = { fg = "#f9555f", bg = "#555555" }

[status]
perm_exec = { fg = "#20af89" }
perm_read = { fg = "#589cf5" }
perm_sep = { fg = "#1e9ee6" }
perm_type = { fg = "#589cf5" }
perm_write = { fg = "#f9555f" }

progress_error = { fg = "#f9555f", bg = "#1c2836" }
progress_label = { fg = "#a1a1a1", bg = "#1c2836" }
progress_normal = { fg = "#a1a1a1", bg = "#1c2836" }

[pick]
active = { fg = "#934d95" }
border = { fg = "#589cf5" }
inactive = { fg = "#a1a1a1" }

[task]
title = { fg = "#589cf5" }
border = { fg = "#589cf5" }
hovered = { fg = "#a1a1a1", bg = "#555555" }

[input]
border = { fg = "#589cf5" }
selected = { bg = "#555555" }

[help]
desc = { fg = "#a1a1a1" }
on = { fg = "#1e9ee6" }
run = { fg = "#934d95" }
hovered = { reversed = true, bold = true }
footer = { fg = "#555555", bg = "#a1a1a1" }

[which]
mask = { bg = "#555555" }
desc = { fg = "#a1a1a1" }
cand = { fg = "#1e9ee6" }
rest = { fg = "#7c2a2f" }

separator_style = { fg = "#888888" }

[notify]
title_info = { fg = "#1e9ee6" }
title_warn = { fg = "#589cf5" }
title_error = { fg = "#f9555f" }

[filetype]
rules = [
  { mime = "image/*", fg = "#589cf5" },
  { mime = "{audio, video}/*", fg = "#20af89" },

  { mime = "application/{pdf,doc,rtf}", fg = "#a1a1a1" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#1e9ee6" },
  { mime = "inode/directory", is = "link", fg = "#1e9ee6" },
  { mime = "*", is = "sock", fg = "#888888" },
  { mime = "*", is = "char", fg = "#fdf029" },
  { mime = "*", is = "exec", fg = "#20af89" },
  { mime = "*", fg = "#a1a1a1" },
  { mime = "inode/directory", fg = "#589cf5" },
]
