# vim: ft=toml
[mgr]
cwd = { fg = "#44b3cc" }

hovered = { reversed = true }
preview_hovered = { underline = true }

find_keyword = { bold = true, fg = "#0000ff" }
find_position = { fg = "#9933cc" }

marker_copied = { fg = "#ccff04", bg = "#ccff04" }
marker_cut = { fg = "#ff6600", bg = "#ff6600" }
marker_selected = { fg = "#0000ff", bg = "#0000ff" }

tab_inactive = { fg = "#cdcdcd" }
tab_active = { fg = "#000000", bg = "#cdcdcd" }

count_copied = { fg = "#000000", bg = "#ccff04" }
count_cut = { fg = "#000000", bg = "#ff6600" }
count_selected = { fg = "#000000", bg = "#0000ff" }

border_style = { fg = "#44b3cc" }

[mode]
normal_main = { fg = "#000000", bg = "#44b3cc", bold = true }
normal_alt = { fg = "#44b3cc", bg = "#555555" }

select_alt = { fg = "#9933cc", bg = "#555555" }
select_main = { fg = "#000000", bg = "#9933cc", bold = true }

unset_main = { fg = "#000000", bg = "#ff6600", bold = true }
unset_alt = { fg = "#ff6600", bg = "#555555" }

[status]
perm_exec = { fg = "#ccff04" }
perm_read = { fg = "#0000ff" }
perm_sep = { fg = "#44b3cc" }
perm_type = { fg = "#44b3cc" }
perm_write = { fg = "#ff6600" }

progress_error = { fg = "#ff6600", bg = "#000000" }
progress_label = { fg = "#cdcdcd", bg = "#000000" }
progress_normal = { fg = "#cdcdcd", bg = "#000000" }

[pick]
active = { fg = "#9933cc" }
border = { fg = "#44b3cc" }
inactive = { fg = "#cdcdcd" }

[task]
title = { fg = "#44b3cc" }
border = { fg = "#44b3cc" }
hovered = { fg = "#cdcdcd", bg = "#555555" }

[input]
border = { fg = "#44b3cc" }
selected = { bg = "#555555" }

[help]
desc = { fg = "#cdcdcd" }
on = { fg = "#44b3cc" }
run = { fg = "#9933cc" }
hovered = { reversed = true, bold = true }
footer = { fg = "#555555", bg = "#cdcdcd" }

[which]
mask = { bg = "#555555" }
desc = { fg = "#cdcdcd" }
cand = { fg = "#44b3cc" }
rest = { fg = "#7f3300" }

separator_style = { fg = "#a5a5a5" }

[notify]
title_info = { fg = "#44b3cc" }
title_warn = { fg = "#0000ff" }
title_error = { fg = "#ff6600" }

[filetype]
rules = [
  { mime = "image/*", fg = "#0000ff" },
  { mime = "{audio, video}/*", fg = "#ccff04" },

  { mime = "application/{pdf,doc,rtf}", fg = "#cdcdcd" },

  { mime = "application/" },

  { mime = "*", is = "link", fg = "#44b3cc" },
  { mime = "inode/directory", is = "link", fg = "#44b3cc" },
  { mime = "*", is = "sock", fg = "#a5a5a5" },
  { mime = "*", is = "char", fg = "#ffcc00" },
  { mime = "*", is = "exec", fg = "#ccff04" },
  { mime = "*", fg = "#cdcdcd" },
  { mime = "inode/directory", fg = "#44b3cc" },
]
